### ISSUE TITLE
Framework to be used

### ISSUE THREAD

**Issue by debasisdwivedy** [airavata-courses/TeamFlash#2]
What frameworks do you think we should follow. I have mentioned a few java based frameworks that we could take into consideration as we are not allowed to use spring:

1.Grail
2.Node JS
3.Struts
4.Spark
5.Play

**Comment by pmpande** [comment]
I think we can go with Node JS.

**Comment by akmehra** [comment]
Yes, I think its a good option. We can use NodeJs for the web framework.

**Comment by girish-gabra** [comment]
So let us finalize Node JS as framework. We can use Java ,Python and Ruby at server-side.
