### ISSUE TITLE
CI/CD for Docker container

### ISSUE THREAD

**Issue by pmpande** [airavata-courses/TeamFlash#37]

**Comment by akmehra** [comment]
While deploying the docker containers on AWS, I was trying to use ECS on AWS but I don't think I am authorized to do so. Could you please confirm if we don't have access to ECS or am I missing something?
@marpierc  @gouravshenoy @anujbhan @smarru

**Comment by marpierc** [comment]
I will check. Note that ECS is not required for project milestone 2.

**Comment by akmehra** [comment]
Thank you for your feedback. But the current issue which we are facing is that if we would dockerize our DB(registry) in a container and then deploy it on AWS, each time whenever a new image of container is built and deployed, the previous registry data is lost. Is it fine if we do not containerize our DB and use RDS and communicate our registry Microservice with that? 
@marpierc

**Comment by marpierc** [comment]
Yes, using RDS is OK.

**Comment by akmehra** [comment]
Thanks a lot for your feedback @marpierc
