### ISSUE TITLE
AWS CI/CD

### ISSUE THREAD

**Issue by akmehra** [airavata-courses/TeamFlash#4]
Understand AWS instance creation. Integrate it with travis CI for CD

**Comment by akmehra** [comment]
The instance is up.
If you want to connect, you will need to download the certificate file attached and then run:

~> ssh -i <Downloaded key> ec2-user@54.205.211.115

if you face an error saying that the permissions on the private key are not right

~> run sudo chmod 600 <file location>
[certificates.zip](https://github.com/airavata-courses/TeamFlash/files/478449/certificates.zip)
[certificates.zip](https://github.com/airavata-courses/TeamFlash/files/478450/certificates.zip)

**Comment by anujbhan** [comment]
@akmehra,

Please take out the private keys from github, delete the keys from AWS and also terminate the instance. This could lead to a security incident.

**Comment by akmehra** [comment]
@anujbhan 
I have removed the keys from github, but when trying to terminate the instance I am getting an error that I am not authorized to do it.

**Comment by debasisdwivedy** [comment]
This issue has been resolved
