### ISSUE TITLE
Reorganize code for Gateway

### ISSUE THREAD

**Issue by akmehra** [airavata-courses/TeamFlash#55]
Reorganize code and structure the branch Gateway

**Comment by debasisdwivedy** [comment]
Updated code!  #cb0b07a

**Comment by debasisdwivedy** [comment]
SHA-cb0b07a

**Comment by debasisdwivedy** [comment]
cb0b07a9858785d3a7790f6b51f03ca2238af1a8

**Comment by debasisdwivedy** [comment]
Completed work and have added new functionality.

Commit - cb0b07a9858785d3a7790f6b51f03ca2238af1a8
