### ISSUE TITLE
Modify Travis.yml file for DataIngestor Service

### ISSUE THREAD

**Issue by pmpande** [airavata-courses/TeamFlash#60]

**Comment by debasisdwivedy** [comment]
#3be33253a6483f95db61e77e9d823fad7798f80b

**Comment by debasisdwivedy** [comment]
3be33253a6483f95db61e77e9d823fad7798f80b

**Comment by debasisdwivedy** [comment]
Updated Travis for Data Ingestor
3be33253a6483f95db61e77e9d823fad7798f80b
