### ISSUE TITLE
Regarding Multiple Language for CI

### ISSUE THREAD

**Issue by akmehra** [airavata-courses/TeamFlash#9]
I am still confused as to how will we have a common yml file for multiple languages. 
Any suggestions? 

@gouravshenoy @marpierc

**Comment by gouravshenoy** [comment]
Hi Abhishek,

There are couple of options for micro-services and their CI/CD:
1. Maintain multiple sub-branches in git for each micro-service, and within
   each sub-branch have a travis file that builds that service. Then during
   deployment, merge all micro-services in a single instance to install the
   application.
2. Have a single branch with different micro-service projects (in different
   languages). Travis provides an option to parallelizing the build process -
   with this you can configure travis to run multiple build types (eg: run
   java using maven & node.js using gradle, etc). See this for more info:
   https://docs.travis-ci.com/user/speeding-up-the-build/#Parallelizing-your-builds-across-virtual-machines

You can decide which option best suites your design. Hope this helps!

Thanks and Regards,
Gourav Shenoy
